default:
  image: node:16.19-bullseye-slim

stages:
  - test
  - snyk-test
  - sonarcloud
  - build-and-push
  - update-ecs-service
  - build-and-push-truepal
  - update-ecs-service-truepal

variables:
  ECS_CLUSTER: default
  ECS_SERVICE: retire-100-eldercare
  APP_NAME: retire-100-eldercare
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  PROJECT_KEY: retire-100-ec

include:
  - template: Code-Quality.gitlab-ci.yml
  - project: "10012/devops/ci-cd-templates"
    file:
      - "/retire-100-eldercare/dev-template.yml"
      - "/retire-100-eldercare/staging-template.yml"
      - "/retire-100-eldercare/prod-template.yml"
      - "/common/snyk.yml"
      - "/common/sonarcloud.yml"
      - "/thetruepal/thetruepal-eldercare/dev-template.yml"
      - "/thetruepal/thetruepal-eldercare/prod-template.yml"

code_quality:
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]
